name: PHP Linting

on:
  push:
    branches: main

jobs:
  phplint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP Lint 8.0
        uses: dbfx/github-phplint/8.0@master
        with:
          folder-to-exclude: '! -path "./vendor/*" ! -path "./folder/excluded/*"'
