name: Lint Python Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Pycodestyle
        run: |
          pip install pycodestyle

      - name: Lint Python files with Pycodestyle
        run: |
          pycodestyle .

      - name: Send SMS Notification
        if: failure()
        run: |
          python - <<EOF

          import requests
          import json

          quicksend_url= "https://ueollosend.com/quicksend/"

          data: {
            'api_key': '${{ secrets.SMS_API_KEY }}',
            'sender_id': 'GitHub',
            'message': 'CI Pipeline has failed, check the details',
            'recipient': '${{ secrets.SMS_RECIPIENT }}'
          }

          headers = {'Content-type': 'application/json'}

          response = requests.post(quicksend_url, headers=headers, json=data)

          with open('sms_response.json', 'w') as f:
            json.dump(response.json(), f, indent=4)
          EOF
